### ISSUE TITLE
Feature request: support sending a json body with http request

### ISSUE THREAD

**Issue by casieo** [marcusolsson/grafana-json-datasource#40]
#39 
In order to use this as a way to get any valuable info from the sprinklr api, it would need to support being able to send a json body.  For example:
`request.AddParameter(@"application/json", "{\n\t\"sinceTime\":" + epochFromInMilliseconds + ",\n\t\"untilTime\":" + epochNowInMilliseconds + ",\n\t\"details\": {\n\t\t\"widgetType\": \"STREAM\"\n\t},\n\t\"messageFormatOptions\": \"strip_html,strip_url\",\n\t\"filters\": [\n\t\t{\n\t\t\t\"dimension\": \"TOPIC\",\n\t\t\t\"filterValues\": [\n\t\t\t\t\"" + definedTopic.Id + "\"\n\t\t\t]\n\t\t},\n\t\t{\n\t\t\t\"dimension\": \"MEDIA_SOURCE\",\n\t\t\t\"filterValues\": [\n\t\t\t\t\"REDDIT\",\n\t\t\t\t\"TWITTER\",\n\t\t\t\t\"FACEBOOK\"\n\t\t\t]\n\t\t}\n\t],\n\t\"metric\": \"MENTIONS\",\n\t\"start\": 0,\n\t\"rows\": 150\n}", ParameterType.RequestBody);` 

I believe many people would find this useful.  Sprinklr is the best enterprise tool for understanding what people are talking about across all public domain social platforms.  This information is valuable for corporations, research, etc.

Please let me know if I can provide any more info.  Thank you!

**Comment by marcusolsson** [comment]
Thank you! I think this should be ok to add. I probably need to experiment with how to add it to the query editor without taking up too much space. Don't know when I'll be able to get around to this, but the more people who vote for this, the sooner it will get done :)

**Comment by smarkm** [comment]
@marcusolsson Does this plugin support source URL query parameter as variable value for `Path` and `Query string`? I think this may be the same kind of issue and follow is what I mean:

**Comment by marcusolsson** [comment]
Judging by the votes on the original post, this is important to many users. I'll get started working on this!

@smarkm I think what you're asking for is a bit different from what the original poster meant. To answer your question though: No, generic query parameter as variables is not supported. If you'd like to accomplish something like this you'd have to use dashboard variables, which _is_ supported in both the path and query string fields.

**Comment by smarkm** [comment]
Got it, Thanks for your answer @marcusolsson

**Comment by marcusolsson** [comment]
Been experimenting with how to add this to the query editor. Here's a few thoughts I've been having so far:

- The body text area is using the Monaco editor so you'd get access to syntax highlight and other features
- I _think_ I'd like to be able to hide it in case of large payloads
- Debating whether selecting JSON in the query editor should add a custom header, or whether that should be configuring in the data source config
- Possible to extend with a key value editor for form values, but thinking a Raw mode would work for now

<img width="872" alt="Screen Shot 2021-01-29 at 12 22 48" src="https://user-images.githubusercontent.com/8396880/106269431-c8b01c80-622c-11eb-9545-65759cef8090.png">

Thoughts?

**Comment by ferencmatyas** [comment]
Hi Marcus, thanks a lot for your plugin. I use the Postman application to test my Icinga queries and the raw body query is a POST request. Per Icinga documentation I add X-HTTP-Method-Override: "GET" in the headers, but this also works in the Grafana datasource. Will this request be executed as POST or GET, or can there be an option to choose?
Thanks a lot!
Regards Ferenc

**Comment by marcusolsson** [comment]
@ferencmatyas All requests are executed as GET. I've been a bit reluctant to add the option to change the HTTP method, since I worry it will extend the scope of the plugin.

The intended purpose of this data source is to read and visualize JSON resources, not to create them. By supporting other methods, I feel like it would encourage people to use it as a Postman alternative.  If you need a control panel, there are other plugins that can send JSON request using a button, for example.

For now, I'd like to keep this plugin read-only. If you can convince me that there are well-used APIs that use POST to read data (I'd like to learn more about the Icinga API), I will consider it. I hope I'm making sense here :)

**Comment by marcusolsson** [comment]
Tried something different altogether. Would love to hear what you think. My reasoning behind this one is that I mostly work on the JSON Paths most of the time, so the path, params, and body would take up unnecessary space.

![tabs](https://user-images.githubusercontent.com/8396880/106354308-3160cd00-62f1-11eb-91a6-a3c10fcc9315.gif)

**Comment by marcusolsson** [comment]
Unfortunately, since technically a GET request with a request body isn't HTTP, browsers don't allow sending bodies with GET requests. 

As I wrote in my earlier comment, I'm familiar with the fact that there are APIs that require it, but based what I've read so far, this simply isn't possible. 

I'm going to (reluctantly) close this issue. If anyone knows how to make non-HTTP requests with the Fetch API, I'll reopen this.

**Comment by marcusolsson** [comment]
Ok, so here's an update on this. I've discussed this thread with the Grafana team, and I've decided to add support for POST requests. The reasoning is that the difference between GET and POST in this case is only semantic. There's nothing stopping you from building a REST API that uses GET to create resources. Similarly, there are APIs that only uses POST for _all_ operations, including reading data.

With that, I also decided to add the support for settings a request body back in there. Unfortunately, due to the browser limitation I mentioned earlier, GET requests don't support a request body. You'll get a warning that tells you the body is being ignored.

I've released v0.9.0, which introduces a brand new query editor. Since this is a pretty big change, I'll hold off on publishing this for a bit to let people try it out first.

You can install it by running:

```
grafana-cli --pluginUrl=https://github.com/marcusolsson/grafana-json-datasource/releases/download/v0.9.0/marcusolsson-json-datasource-0.9.0.zip plugins install marcusolsson-json-datasource
```

Please read the [CHANGELOG.md](https://github.com/marcusolsson/grafana-json-datasource/blob/8f918cd5a32fb1f5c5345b75212b9b685ef7e2cd/CHANGELOG.md) before installing it.

**Comment by ferencmatyas** [comment]
@marcusolsson , thanks a lot for this update. I updated the plugin, the request goes out as a GET. How can I change the request to POST? Maybe as a query option? [2021-02-01 11:51:32 +0100] information/HttpServerConnection: Request: GET /v1/objects/services?filter=service.state==ServiceWarning (from [...]:...), user: ..., agent: Grafana/7.3.7, status: OK).
Thank you.

**Comment by ferencmatyas** [comment]
@marcusolsson thanks a lot for this update, I noticed the drop-down menu on the Path tab, it works perfectly with 2 Panels in Grafana.

**Comment by ferencmatyas** [comment]
@marcusolsson I write a new reply. the Path query above does not solve the issue with auto refresh, I need for Icinga the body part to send the query for Critical or Warning for it to consider the other filters. Now when I refresh the Grafana Dashboard the initial data is fine and I see 2 http requests in the icinga log. But when Grafana does the Auto Refresh, no new http request is seen in the icinga log and Grafana somehow loads the same cached reply. I googled maybe this is a Grafana setting, this comes up https://community.grafana.com/t/refresh-every-5s/3897/8 . Can you reproduce this issue? Thank you.

**Comment by marcusolsson** [comment]
By default, the plugin caches the response for 5 minutes. This is to avoid making requests while working on your JSON Paths, once you're happy with your query, I suggest that you change the Cache Time to `0s`. Let me know if that helps!

**Comment by ferencmatyas** [comment]
@marcusolsson brilliant, with Cache Time 0s works, thank you!

**Comment by casieo** [comment]
> Ok, so here's an update on this. I've discussed this thread with the Grafana team, and I've decided to add support for POST requests. The reasoning is that the difference between GET and POST in this case is only semantic. There's nothing stopping you from building a REST API that uses GET to create resources. Similarly, there are APIs that only uses POST for _all_ operations, including reading data.
> 
> With that, I also decided to add the support for settings a request body back in there. Unfortunately, due to the browser limitation I mentioned earlier, GET requests don't support a request body. You'll get a warning that tells you the body is being ignored.
> 
> I've released v0.9.0, which introduces a brand new query editor. Since this is a pretty big change, I'll hold off on publishing this for a bit to let people try it out first.
> 
> You can install it by running:
> 
> ```
> grafana-cli --pluginUrl=https://github.com/marcusolsson/grafana-json-datasource/releases/download/v0.9.0/marcusolsson-json-datasource-0.9.0.zip plugins install marcusolsson-json-datasource
> ```
> 
> Please read the [CHANGELOG.md](https://github.com/marcusolsson/grafana-json-datasource/blob/8f918cd5a32fb1f5c5345b75212b9b685ef7e2cd/CHANGELOG.md) before installing it.

This is working beautifully!  Thank you!  Will also play with word cloud panel, etc.
![sprinklr](https://user-images.githubusercontent.com/14110178/107107208-8c5c5d80-67e4-11eb-9d8d-b004571e20ab.JPG)
